runtime: python27
api_version: 1
threadsafe: true

libraries:
        - name: webapp2
          version: latest
        - name: jinja2
          version: latest

handlers:
        - url: /templates
          static_dir: templates
          application_readable: true

        - url: /bootstrap
          static_dir: bootstrap

        - url: /.*
          script: handlers.main.application
